spring:
  config:
    activate:
      on-profile: dev
  sql:
    init:
      platform: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: newUser
    password: pass123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      default_schema: public
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    database-platform:
    properties:
      hibernate:
        format_sql: false
    show-sql: true

workingEnvironment: dev

access:
  cors:
    allowed-origins: "*"

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
---