
CREATE TABLE IF NOT EXISTS public.employee
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    department character varying(50) COLLATE pg_catalog."default",
    employee_name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT employee_pkey PRIMARY KEY (id),
    CONSTRAINT uk_gvmo0nv657mx8nlov8cnpyg01 UNIQUE (employee_name)
);

CREATE TABLE IF NOT EXISTS public.skill
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    skill_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT skill_pkey PRIMARY KEY (id),
    CONSTRAINT skill_name_unique_idx UNIQUE (skill_name)
);

CREATE TABLE IF NOT EXISTS public.skill_rating
(
    employee_id bigint NOT NULL,
    skill_id bigint NOT NULL,
    rating integer,
    CONSTRAINT skill_rating_pkey PRIMARY KEY (employee_id, skill_id),
    CONSTRAINT fkl2rk7y1936bwcrabut1owpl6q FOREIGN KEY (employee_id)
    REFERENCES public.employee (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION,
    CONSTRAINT fksc5ijuh61th3n58tqjagjvcw0 FOREIGN KEY (skill_id)
    REFERENCES public.skill (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
);